<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="*">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<ProjectReference Include="../../src/Persistence.EntityFramework/Persistence.EntityFramework.csproj" />
		<ProjectReference Include="../../src/Persistence.EntityFramework.Migrations/Persistence.EntityFramework.Migrations.csproj" />
		<ProjectReference Include="../../src/Persistence.EntityFramework.SqlServer/Persistence.EntityFramework.SqlServer.csproj" />
		<ProjectReference Include="../../src/Persistence.EntityFramework.Migrations.SqlServer.Generator/Persistence.EntityFramework.Migrations.SqlServer.Generator.csproj" />
	</ItemGroup>
</Project>
