using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Migrations.Design;
using Microsoft.Extensions.DependencyInjection;

namespace Norse.Persistence.EntityFramework.Design.Tests;

public sealed class DdlEmittingMigrationsScaffolderTests
{
	[Fact]
	void ScaffoldMigration_delegates_to_inner_scaffolder_and_returns_its_result()
	{
		FakeMigrationsScaffolder inner = new();
		using var ctx = CreateContext();
		var outputPath = TempFilePath();
		DdlEmittingMigrationsScaffolder sut = new(inner, CurrentDbContext(ctx), outputPath);

		try
		{
			var result = sut.ScaffoldMigration("Initial", "MyNamespace");

			inner.ScaffoldMigrationCallCount.ShouldBe(1);
			result.MigrationId.ShouldBe("20260722000000_Test");
		}
		finally
		{
			File.Delete(outputPath);
		}
	}

	[Fact]
	void ScaffoldMigration_writes_a_ddl_file_headed_with_the_auto_generated_banner()
	{
		FakeMigrationsScaffolder inner = new();
		using var ctx = CreateContext();
		var outputPath = TempFilePath();
		DdlEmittingMigrationsScaffolder sut = new(inner, CurrentDbContext(ctx), outputPath);

		try
		{
			sut.ScaffoldMigration("Initial", "MyNamespace");

			var written = File.ReadAllText(outputPath);
			written.ShouldContain("AUTO-GENERATED BY EF CORE MIGRATIONS");
			written.ShouldContain("CREATE TABLE");
			written.ShouldContain("StubEntities");
		}
		finally
		{
			File.Delete(outputPath);
		}
	}

	[Fact]
	void ScaffoldMigration_writes_the_ddl_file_as_utf8_without_a_bom()
	{
		FakeMigrationsScaffolder inner = new();
		using var ctx = CreateContext();
		var outputPath = TempFilePath();
		DdlEmittingMigrationsScaffolder sut = new(inner, CurrentDbContext(ctx), outputPath);

		try
		{
			sut.ScaffoldMigration("Initial", "MyNamespace");

			byte[] bom = [0xEF, 0xBB, 0xBF];
			var bytes = File.ReadAllBytes(outputPath);
			bytes.Take(3).ShouldNotBe(bom);
		}
		finally
		{
			File.Delete(outputPath);
		}
	}

	[Fact]
	void ScaffoldMigration_creates_the_output_directory_when_it_does_not_exist()
	{
		FakeMigrationsScaffolder inner = new();
		using var ctx = CreateContext();
		var outputDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
		var outputPath = Path.Combine(outputDir, "schema.sql");
		DdlEmittingMigrationsScaffolder sut = new(inner, CurrentDbContext(ctx), outputPath);

		try
		{
			sut.ScaffoldMigration("Initial", "MyNamespace");

			Directory.Exists(outputDir).ShouldBeTrue();
			File.Exists(outputPath).ShouldBeTrue();
		}
		finally
		{
			Directory.Delete(outputDir, recursive: true);
		}
	}

	[Fact]
	void RemoveMigration_delegates_to_inner_scaffolder_and_re_emits_ddl()
	{
		FakeMigrationsScaffolder inner = new();
		using var ctx = CreateContext();
		var outputPath = TempFilePath();
		DdlEmittingMigrationsScaffolder sut = new(inner, CurrentDbContext(ctx), outputPath);

		try
		{
			sut.RemoveMigration("projectDir", "MyNamespace", force: false, language: "C#");

			inner.RemoveMigrationCallCount.ShouldBe(1);
			File.Exists(outputPath).ShouldBeTrue();
		}
		finally
		{
			File.Delete(outputPath);
		}
	}

	[Fact]
	void Save_delegates_to_inner_scaffolder_without_re_emitting_ddl()
	{
		FakeMigrationsScaffolder inner = new();
		using var ctx = CreateContext();
		var outputPath = TempFilePath();
		DdlEmittingMigrationsScaffolder sut = new(inner, CurrentDbContext(ctx), outputPath);
		ScaffoldedMigration migration = new("cs", null, "", "id", "", "", "", "", "");

		sut.Save("projectDir", migration, null);

		inner.SaveCallCount.ShouldBe(1);
		File.Exists(outputPath).ShouldBeFalse();
	}

	static string TempFilePath() =>
		Path.Combine(Path.GetTempPath(), $"{Guid.NewGuid()}.sql");

	static StubContext CreateContext() =>
		new(new DbContextOptionsBuilder<StubContext>().UseSqlite("Data Source=:memory:").Options);

	static ICurrentDbContext CurrentDbContext(DbContext ctx) =>
		((IInfrastructure<IServiceProvider>)ctx).Instance.GetRequiredService<ICurrentDbContext>();

	sealed class StubContext(DbContextOptions<StubContext> options) : NorseDbContext(options)
	{
		public DbSet<StubEntity> StubEntities => Set<StubEntity>();
	}

	sealed record StubEntity : INorseEntity<StubEntity>
	{
		public int Id { get; init; }

		public static void Configure(EntityTypeBuilder<StubEntity> builder)
		{
		}
	}
}
