using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Norse.Persistence.EntityFramework.Generator;

[Generator]
public sealed class EntityConfigurationApplicationGenerator : IIncrementalGenerator
{
	const string NorseEntityNamespace = "Norse.Persistence.EntityFramework";
	const string NorseEntityInterfaceMetadataName = "INorseEntity`1";
	const string NorseDbContextMetadataName = "Norse.Persistence.EntityFramework.NorseDbContext";

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var entityDeclarations = context.SyntaxProvider.CreateSyntaxProvider(
			static (node, _) => node is ClassDeclarationSyntax { TypeParameterList: null },
			static (ctx, _) => (ClassDeclarationSyntax)ctx.Node);

		var compilationAndClasses = context.CompilationProvider.Combine(entityDeclarations.Collect());

		context.RegisterSourceOutput(compilationAndClasses, static (ctx, source) =>
		{
			var (compilation, classes) = source;
			var entities = FindEntities(compilation, classes);
			var tier1Context = FindPartialTier1Context(compilation, classes);

			if (entities.Count == 0 && tier1Context is null)
				return;

			var text = BuildSource(entities, tier1Context);
			ctx.AddSource("NorseEntityConfigurationExtensions.g.cs", SourceText.From(text, Encoding.UTF8));
		});
	}

	static IList<string> FindEntities(Compilation compilation, IList<ClassDeclarationSyntax> classes)
	{
		IList<string> results = [];

		foreach (var classDeclaration in classes)
		{
			var model = compilation.GetSemanticModel(classDeclaration.SyntaxTree);
			if (model.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol type)
				continue;

			if (type.IsAbstract)
				continue;

			var implementsSelf = type.AllInterfaces.Any(i =>
				i.OriginalDefinition.MetadataName == NorseEntityInterfaceMetadataName &&
				i.OriginalDefinition.ContainingNamespace?.ToDisplayString() == NorseEntityNamespace &&
				i.TypeArguments.Length == 1 &&
				SymbolEqualityComparer.Default.Equals(i.TypeArguments[0], type));

			if (implementsSelf)
				results.Add(type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
		}

		return results;
	}

	static INamedTypeSymbol? FindPartialTier1Context(Compilation compilation, IList<ClassDeclarationSyntax> classes)
	{
		foreach (var classDeclaration in classes)
		{
			if (!classDeclaration.Modifiers.Any(SyntaxKind.PartialKeyword))
				continue;

			var model = compilation.GetSemanticModel(classDeclaration.SyntaxTree);
			if (model.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol type)
				continue;

			if (InheritsNorseDbContext(type))
				return type;
		}

		return null;
	}

	static bool InheritsNorseDbContext(INamedTypeSymbol type)
	{
		for (var current = type.BaseType; current is not null; current = current.BaseType)
			if (current.ToDisplayString() == NorseDbContextMetadataName)
				return true;

		return false;
	}

	static string BuildSource(IList<string> entities, INamedTypeSymbol? tier1Context)
	{
		StringBuilder sb = new();
		sb.AppendLine("// <auto-generated />");
		sb.AppendLine("#nullable enable");
		sb.AppendLine("using Microsoft.EntityFrameworkCore;");
		sb.AppendLine();
		sb.AppendLine("internal static class GeneratedNorseModelConfigurations");
		sb.AppendLine("{");
		sb.AppendLine("\tpublic static ModelBuilder ApplyNorseConfigurations(this ModelBuilder builder)");
		sb.AppendLine("\t{");

		foreach (var entity in entities)
			sb.AppendLine($"\t\tbuilder.Entity<{entity}>(eb => {entity}.Configure(eb));");

		sb.AppendLine("\t\treturn builder;");
		sb.AppendLine("\t}");
		sb.AppendLine("}");

		if (tier1Context is not null)
		{
			var isGlobalNamespace = tier1Context.ContainingNamespace.IsGlobalNamespace;
			var indent = isGlobalNamespace ? "" : "\t";

			sb.AppendLine();
			if (!isGlobalNamespace)
			{
				sb.AppendLine($"namespace {tier1Context.ContainingNamespace.ToDisplayString()}");
				sb.AppendLine("{");
			}

			sb.AppendLine($"{indent}partial class {tier1Context.Name}");
			sb.AppendLine($"{indent}{{");
			sb.AppendLine($"{indent}\tprotected override void ConfigureNorseEntities(ModelBuilder builder)");
			sb.AppendLine($"{indent}\t{{");
			sb.AppendLine($"{indent}\t\tbase.ConfigureNorseEntities(builder);");
			sb.AppendLine($"{indent}\t\tbuilder.ApplyNorseConfigurations();");
			sb.AppendLine($"{indent}\t}}");
			sb.AppendLine($"{indent}}}");

			if (!isGlobalNamespace)
				sb.AppendLine("}");
		}

		return sb.ToString();
	}
}
