using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Norse.EntityFramework.Configuration.Generator;

[Generator]
public sealed class EntityConfigurationApplicationGenerator : IIncrementalGenerator
{
	const string NorseEntityNamespace = "Norse.EntityFramework";
	const string NorseEntityInterfaceMetadataName = "INorseEntity`1";
	const string NorseDbContextMetadataName = "Norse.EntityFramework.NorseDbContext";

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var entityDeclarations = context.SyntaxProvider.CreateSyntaxProvider(
			static (node, _) => node is ClassDeclarationSyntax { TypeParameterList: null },
			static (ctx, _) => (ClassDeclarationSyntax)ctx.Node);

		var compilationAndClasses = context.CompilationProvider.Combine(entityDeclarations.Collect());

		context.RegisterSourceOutput(compilationAndClasses, static (ctx, source) =>
		{
			var (compilation, classes) = source;
			var entities = FindEntities(compilation, classes);
			var tier1Context = FindPartialTier1Context(compilation, classes);

			if (entities.Count == 0 && tier1Context is null)
				return;

			var text = BuildSource(entities, tier1Context);
			ctx.AddSource("NorseEntityConfigurationExtensions.g.cs", SourceText.From(text, Encoding.UTF8));
		});
	}

	static IList<string> FindEntities(Compilation compilation, IList<ClassDeclarationSyntax> classes)
	{
		IList<string> results = [];

		foreach (var classDeclaration in classes)
		{
			var model = compilation.GetSemanticModel(classDeclaration.SyntaxTree);
			if (model.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol type)
				continue;

			if (type.IsAbstract)
				continue;

			var implementsSelf = type.AllInterfaces.Any(i =>
				i.OriginalDefinition.MetadataName == NorseEntityInterfaceMetadataName &&
				i.OriginalDefinition.ContainingNamespace?.ToDisplayString() == NorseEntityNamespace &&
				i.TypeArguments.Length == 1 &&
				SymbolEqualityComparer.Default.Equals(i.TypeArguments[0], type));

			if (implementsSelf)
				results.Add(type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
		}

		return results;
	}

	static string? FindPartialTier1Context(Compilation compilation, IList<ClassDeclarationSyntax> classes)
	{
		foreach (var classDeclaration in classes)
		{
			if (!classDeclaration.Modifiers.Any(SyntaxKind.PartialKeyword))
				continue;

			var model = compilation.GetSemanticModel(classDeclaration.SyntaxTree);
			if (model.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol type)
				continue;

			if (InheritsNorseDbContext(type))
				return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
		}

		return null;
	}

	static bool InheritsNorseDbContext(INamedTypeSymbol type)
	{
		for (var current = type.BaseType; current is not null; current = current.BaseType)
			if (current.ToDisplayString() == NorseDbContextMetadataName)
				return true;

		return false;
	}

	static string BuildSource(IList<string> entities, string? tier1Context)
	{
		StringBuilder sb = new();
		sb.AppendLine("// <auto-generated />");
		sb.AppendLine("#nullable enable");
		sb.AppendLine("using Microsoft.EntityFrameworkCore;");
		sb.AppendLine();
		sb.AppendLine("internal static class GeneratedNorseModelConfigurations");
		sb.AppendLine("{");
		sb.AppendLine("\tpublic static ModelBuilder ApplyNorseConfigurations(this ModelBuilder builder)");
		sb.AppendLine("\t{");

		foreach (var entity in entities)
			sb.AppendLine($"\t\tbuilder.Entity<{entity}>(eb => {entity}.Configure(eb));");

		sb.AppendLine("\t\treturn builder;");
		sb.AppendLine("\t}");
		sb.AppendLine("}");

		if (tier1Context is not null)
		{
			sb.AppendLine();
			sb.AppendLine($"partial class {StripGlobalPrefix(tier1Context)}");
			sb.AppendLine("{");
			sb.AppendLine("\tprotected override void ConfigureNorseEntities(ModelBuilder builder)");
			sb.AppendLine("\t{");
			sb.AppendLine("\t\tbase.ConfigureNorseEntities(builder);");
			sb.AppendLine("\t\tbuilder.ApplyNorseConfigurations();");
			sb.AppendLine("\t}");
			sb.AppendLine("}");
		}

		return sb.ToString();
	}

	static string StripGlobalPrefix(string fullyQualifiedName) =>
		fullyQualifiedName.StartsWith("global::", StringComparison.Ordinal)
			? fullyQualifiedName.Substring("global::".Length)
			: fullyQualifiedName;
}
