using System.Text;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations.Design;

namespace Norse.Persistence.EntityFramework.Design;

/// <summary>
/// Decorates EF Core's own <see cref="IMigrationsScaffolder"/>: every <see cref="ScaffoldMigration"/>
/// or <see cref="RemoveMigration"/> call also writes the current-state schema as plain DDL to
/// <paramref name="outputFilePath"/> (via the constructor), so a DBA fluent in SQL but not C# can
/// review the schema without reading migration Designer files. Raw <c>GenerateCreateScript()</c>
/// passthrough -- no schema-guard cleanup, since nothing compiles this file yet (no <c>Microsoft.Build.Sql</c>
/// project consumes it; see the design doc, deferred until a realm actually needs one).
/// </summary>
sealed class DdlEmittingMigrationsScaffolder(
	IMigrationsScaffolder inner,
	ICurrentDbContext currentContext,
	string outputFilePath) : IMigrationsScaffolder
{
	public ScaffoldedMigration ScaffoldMigration(string migrationName, string? rootNamespace, string? subNamespace = null, string? language = null, bool dryRun = false)
	{
		var result = inner.ScaffoldMigration(migrationName, rootNamespace, subNamespace, language, dryRun);
		EmitDdl();
		return result;
	}

	public MigrationFiles RemoveMigration(string projectDir, string? rootNamespace, bool force, string? language, bool dryRun = false, bool offline = false)
	{
		var result = inner.RemoveMigration(projectDir, rootNamespace, force, language, dryRun, offline);
		EmitDdl();
		return result;
	}

	public MigrationFiles Save(string projectDir, ScaffoldedMigration migration, string? outputDir, bool dryRun = false) =>
		inner.Save(projectDir, migration, outputDir, dryRun);

	void EmitDdl()
	{
		var directory = Path.GetDirectoryName(outputFilePath);
		if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
			Directory.CreateDirectory(directory);

		StringBuilder sb = new(
			"""
			-- ============================================================
			-- AUTO-GENERATED BY EF CORE MIGRATIONS — DO NOT EDIT BY HAND
			-- Changes made here will be overwritten on the next migration.
			-- Run: dotnet ef migrations add <Name> to update this file.
			-- ============================================================

			""");
		sb.Append(currentContext.Context.Database.GenerateCreateScript());

		File.WriteAllText(outputFilePath, sb.ToString(), Encoding.UTF8);
	}
}
