using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Norse.EntityFramework.Migrations.Generator.Shared;

namespace Norse.EntityFramework.Migrations.PostgreSQL.Generator;

[Generator]
public sealed class MigrationContributorGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var contributors = context.CompilationProvider.Select(static (compilation, _) =>
			MigrationContributorDiscovery.FindContributors(compilation));

		context.RegisterSourceOutput(contributors, static (ctx, list) =>
		{
			if (list.Count == 0)
				return;

			var source = BuildSource(list);
			ctx.AddSource("NorseMigrationsExtensions.g.cs", SourceText.From(source, Encoding.UTF8));
		});
	}

	static string BuildSource(IList<ContributorInfo> contributors)
	{
		StringBuilder sb = new();
		sb.AppendLine("// <auto-generated />");
		sb.AppendLine("#nullable enable");
		sb.AppendLine("using Microsoft.EntityFrameworkCore;");
		sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
		sb.AppendLine("using Microsoft.Extensions.Hosting;");
		sb.AppendLine("using Norse.Abstractions.Migrations;");
		sb.AppendLine("using Norse.EntityFramework.PostgreSQL;");
		sb.AppendLine("using Norse.Infrastructure.Migrations;");
		sb.AppendLine();
		sb.AppendLine("static class NorseMigrationsGeneratedExtensions");
		sb.AppendLine("{");
		sb.AppendLine("\tpublic static global::Microsoft.Extensions.Hosting.IHostApplicationBuilder AddNorseMigrations(");
		sb.AppendLine("\t\tthis global::Microsoft.Extensions.Hosting.IHostApplicationBuilder builder)");
		sb.AppendLine("\t{");

		foreach (var c in contributors)
		{
			sb.AppendLine($"\t\tbuilder.AddNorsePostgresMigrationContext<{c.ContextType}>(\"{c.ConnectionStringName}\", \"{c.MigrationsAssemblyName}\");");
			sb.AppendLine($"\t\tbuilder.Services.AddTransient<global::Norse.Abstractions.Migrations.IMigrationContributor, {c.ContributorType}>();");
		}

		sb.AppendLine("\t\tbuilder.AddNorseMigrationsRunner();");
		sb.AppendLine("\t\treturn builder;");
		sb.AppendLine("\t}");
		sb.AppendLine("}");

		return sb.ToString();
	}
}
