<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="11.*-*" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="11.*-*" />
		<ProjectReference Include="../../src/EntityFramework/EntityFramework.csproj" />
	</ItemGroup>
</Project>
