<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="*">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<ProjectReference Include="../../src/Persistence.EntityFramework/Persistence.EntityFramework.csproj" />
		<ProjectReference Include="../../src/Persistence.EntityFramework.Generator/Persistence.EntityFramework.Generator.csproj" />
	</ItemGroup>
</Project>
