<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="11.*-*" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="11.*-*" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="11.*-*" />
		<ProjectReference Include="../../src/Persistence.EntityFramework.Migrations/Persistence.EntityFramework.Migrations.csproj" />
	</ItemGroup>
</Project>
